### ISSUE TITLE
DPI display scaling is ignored

### ISSUE THREAD

**Issue by milahu** [lapce/lapce#1458]
part of #20
different than #785

## Lapce Version

cb7b8ac70098ba2ee59a674604555cab48660671

## System information

linux, kde plasma desktop

## Describe the bug

DPI display scaling is ignored

## Additional information

on a kde plasma desktop with 150% dpi scaling ...

```console
$ echo $QT_SCREEN_SCALE_FACTORS
LVDS1=1.5;DP1=1.5;DP2=1.5;DP3=1.5;HDMI1=1.5;HDMI2=1.5;HDMI3=1.5;VGA1=1.5;VIRTUAL1=1.5;
```

lapce
main app has wrong scaling = too small 
context menus have correct scaling

<img width=692 src=https://user-images.githubusercontent.com/12958815/194717078-f49ed750-074b-4eaa-adca-1659d62d7f04.png title="screenshot lapce dpi scaling">

gtk3-demo-application

<img width=336 src=https://user-images.githubusercontent.com/12958815/194717661-8d0a480e-dfe7-4932-86b3-d6c70800a250.png title="screenshot gtk3-demo-application dpi scaling">

vscodium

<img width=695 src=https://user-images.githubusercontent.com/12958815/194717305-9a8cce9b-c99a-46c7-893a-bcf507026227.png title="screenshot vscodium dpi scaling">

**Comment by virtualritz** [comment]
This is the only reason I (still) can't use this editor.
It was an issue on macOS (maybe fixed now?) but it definitely still is an issue on Linux which I'm on now (Kubuntu 22.04).

My scaling is also 150%.

**Comment by virtualritz** [comment]
Bump.

**Comment by NightEule5** [comment]
[druid#1751](https://github.com/linebender/druid/pull/1751) appears to be related, maybe updating the druid fork would fix it?

**Comment by ctron** [comment]
I am running into the same issue. Unfortunately there seems to be no way to influence the scaling manually.

**Comment by milahu** [comment]
still an issue with lapce 0.2.8

> [druid#1751](https://github.com/linebender/druid/pull/1751) appears to be related, maybe updating the druid fork would fix it?

lapce is now based on [floem](https://github.com/lapce/floem), see also #2011

**Comment by chris-aeviator** [comment]
it's pretty unusable in that size - just downloaded it and that's my experience 

![grafik](https://github.com/lapce/lapce/assets/11522213/61bce619-986a-43d0-a48c-f4aca6ca0ec2)

**Comment by jessestippel** [comment]
Also getting this issue in Ubuntu with a hidpi display at 200% scaling. The whole UI is completely unusable, this seems to only be happening since the recent UI changes.

**Comment by panekj** [comment]
> apparently floem does support scaling via `app_state.scale`

and it's available in lapce, but it's not synced with system DPI

https://github.com/lapce/lapce/blob/631eebfb563f18402eff10421570deb0d8f07882/defaults/keymaps-nonmacos.toml#L30-L36
https://github.com/lapce/lapce/blob/631eebfb563f18402eff10421570deb0d8f07882/defaults/keymaps-macos.toml#L34-L40

**Comment by virtualritz** [comment]
> and it's available in lapce, but it's not synced with system DPI
> 
> https://github.com/lapce/lapce/blob/631eebfb563f18402eff10421570deb0d8f07882/defaults/keymaps-nonmacos.toml#L30-L36

I added those to my `~/.config/lapce-stable/keymaps.toml` but they do not work/do nothing (I'm on Linux). What am I missing?

**Comment by 12c76dc** [comment]
The mentioned keyboard shortcuts works, but after restarting Lapce, I need to apply scaling again. Can I somehow make it to keep it? Or is it no implemented yet?

**Comment by Netroxen** [comment]
> The mentioned keyboard shortcuts works, but after restarting Lapce, I need to apply scaling again. Can I somehow make it to keep it? Or is it no implemented yet?

As far as I see: https://github.com/lapce/lapce/blob/master/lapce-app/src/window_tab.rs#L1063
There doesn't seem to be a hook for saving/storing the zoom values anywhere. I suppose it would be nice if we could set this as a launch parameter.

There are 2 sides to this issue. 1) The app scaling itself. 2) The QT window scaling. 
Would be nice to have a solution for this all, as it's the only reason I'm not using Lapce since the UI upgrade.

**Comment by panekj** [comment]
> Or is it no implemented yet?

It is now (https://github.com/lapce/lapce/commit/faf8c9ba92d415d564009382fd9280b464d0d263)

**Comment by hpux735** [comment]
I just built from f25a8 (head as of June 17), and it seems like this might still not be solved?  Here's a screenshot showing the lapce main window editor (10pt font), a menu dialog in lapce, and a native window from the gnome file manager.  It seems like Lapce is still struggling with system dpi settings. 
![image](https://github.com/lapce/lapce/assets/1170900/41879a49-6f36-4ec5-9df6-8635c7cedd09)

**Comment by panekj** [comment]
> I just built from f25a8 (head as of June 17), and it seems like this might still not be solved?

It was never fixed
